### ISSUE TITLE
How does dyno-queues make sure that message would be consumed only once.

### ISSUE THREAD

**Issue by wangweiqing** [Netflix/dyno-queues#8]
Hi, I wanna to find a easy delay queue for my application.Then I find your dyno-quues.
I read your blog and code, I find there is maybe a problem about message being consumed.
When pop, you use peekIds() method to get from redis.
`
private Set<String> peekIds(int offset, int count) {
		
		return execute(() -> {
			double now = Long.valueOf(System.currentTimeMillis() + 1).doubleValue();
			Set<String> scanned = quorumConn.zrangeByScore(myQueueShard, 0, now, offset, count);
			return scanned;
		});
		
	}`
Then you remove them in _pop() method.
`
long removed = quorumConn.zrem(myQueueShard, msgId);
			if (removed == 0) {
				if (logger.isDebugEnabled()) {
					logger.debug("cannot remove from the queue shard " + msgId);
				}
				monitor.misses.increment();
				continue;
			}`
My question is that if I consume those messages with multi consumers, how to make sure that each message will be consumed once during peekIds() and _pop(). It seems like one message could be get by different consumer.

**Comment by v1r3n** [comment]
You can use dyno-queues with multiple consumers per queue, the pop implementation ensures a message is delivered to only one of the consumers.  dyno-queues achieves this by relying on the underlying redis/dynomite architecture to ensure writes to a sorted set will return back 0 or 1 depending upon if the write operation adds a new element or not (if already added by another thread/process).  Hence the checks in the pop() method to ensure writes succeeds. 

We run dynomite with DC_QUORUM_SAFE consistency level to ensure this behavior.

**Comment by wangweiqing** [comment]
oh, I see, good idea.
